mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
geodata-loader: memconservative

proxies:
  - name: "Reality-154.17.234.37"
    type: vless
    server: "154.17.234.37"
    port: 8443
    uuid: "f5f73b3a-1eee-4d90-80ef-8b2ae3535f48"
    udp: true
    tls: true
    network: tcp
    flow: "xtls-rprx-vision"
    packet-encoding: xudp
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "c9d-S2G_iiNIAZ0ip8P1_RIjHbRNZe1jbSUP_DNDUm8"
      short-id: "0a79af70ac4f2127"
    encryption: none

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - "Reality-154.17.234.37"
      - DIRECT

rules:
  - DOMAIN,localhost,DIRECT
  - DOMAIN-SUFFIX,local,DIRECT
  - DOMAIN-SUFFIX,lan,DIRECT
  - DOMAIN-SUFFIX,cn,DIRECT
  - GEOSITE,private,DIRECT
  - GEOSITE,cn,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR,169.254.0.0/16,DIRECT,no-resolve
  - IP-CIDR6,::1/128,DIRECT,no-resolve
  - IP-CIDR6,fc00::/7,DIRECT,no-resolve
  - IP-CIDR6,fe80::/10,DIRECT,no-resolve
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,PROXY
